export enum ReportType {
  PACIENTES_INTERNADOS = 'PACIENTES_INTERNADOS',
  TAXA_OCUPACAO_LEITOS = 'TAXA_OCUPACAO_LEITOS',
  PACIENTES_POR_ALA = 'PACIENTES_POR_ALA',
  HISTORICO_MEDICAMENTOS = 'HISTORICO_MEDICAMENTOS',
  ADMINISTRACAO_MEDICAMENTO_HORARIO = 'ADMINISTRACAO_MEDICAMENTO_HORARIO',
  EXAMES_REALIZADOS = 'EXAMES_REALIZADOS',
  TEMPO_MEDIO_INTERNACAO = 'TEMPO_MEDIO_INTERNACAO',
  AGENDA_DO_DIA = 'AGENDA_DO_DIA',
  FATURAMENTO_POR_CONVENIO = 'FATURAMENTO_POR_CONVENIO',
}