export type PermissionsMap = Record<string, Record<string, boolean>>;

export interface PermissionTemplate {
  label: string;
  descricao: string;
  cor: string;
  icone: string;
  permissoes: PermissionsMap;
}

export const PERMISSION_TEMPLATES: Record<string, PermissionTemplate> = {
  ADMINISTRADOR: {
    label: 'Administrador',
    descricao: 'Acesso total ao sistema — TI e Direção',
    cor: '#ff4d4f',
    icone: 'CrownOutlined',
    permissoes: {
      pacientes:   { criar: true,  editar: true,  visualizar: true,  excluir: true  },
      agendamento: { criar: true,  editar: true,  visualizar: true,  cancelar: true },
      prontuario:  { criar: true,  editar: true,  visualizar: true,  excluir: true  },
      prescricao:  { criar: true,  editar: true,  visualizar: true,  excluir: true  },
      medicacao:   { administrar: true, visualizar: true, criar: true, editar: true  },
      exames:      { solicitar: true, liberar: true, visualizar: true, criar: true   },
      internacao:  { admitir: true, alta: true, visualizar: true, criar: true        },
      medicos:     { criar: true,  editar: true,  visualizar: true,  excluir: true   },
      enfermeiros: { criar: true,  editar: true,  visualizar: true,  excluir: true   },
      usuarios:    { criar: true,  editar: true,  visualizar: true,  excluir: true   },
      alas:        { criar: true,  editar: true,  visualizar: true,  excluir: true   },
      leitos:      { criar: true,  editar: true,  visualizar: true,  excluir: true   },
      faturamento: { criar: true,  editar: true,  visualizar: true,  excluir: true   },
      relatorios:  { visualizar: true, exportar: true                                },
      roles:       { criar: true,  editar: true,  visualizar: true,  excluir: true   },
      sistema:     { administrar: true                                               },
    },
  },
  MEDICO: {
    label: 'Médico',
    descricao: 'Prescrição, prontuário e solicitação de exames',
    cor: '#1677ff',
    icone: 'MedicineBoxOutlined',
    permissoes: {
      pacientes:   { criar: true,  editar: true,  visualizar: true,  excluir: false },
      agendamento: { criar: true,  editar: true,  visualizar: true,  cancelar: true },
      prontuario:  { criar: true,  editar: true,  visualizar: true,  excluir: false },
      prescricao:  { criar: true,  editar: true,  visualizar: true,  excluir: false },
      medicacao:   { administrar: false, visualizar: true, criar: false, editar: false },
      exames:      { solicitar: true, liberar: false, visualizar: true, criar: false  },
      internacao:  { admitir: true, alta: true, visualizar: true, criar: true         },
      medicos:     { criar: false, editar: false, visualizar: true,  excluir: false   },
      enfermeiros: { criar: false, editar: false, visualizar: true,  excluir: false   },
      usuarios:    { criar: false, editar: false, visualizar: false, excluir: false   },
      alas:        { criar: false, editar: false, visualizar: true,  excluir: false   },
      leitos:      { criar: false, editar: false, visualizar: true,  excluir: false   },
      faturamento: { criar: false, editar: false, visualizar: false, excluir: false   },
      relatorios:  { visualizar: true, exportar: false                                },
      roles:       { criar: false, editar: false, visualizar: false, excluir: false   },
      sistema:     { administrar: false                                               },
    },
  },
  ENFERMEIRO: {
    label: 'Enfermeiro(a)',
    descricao: 'Administração de medicação, evolução e triagem',
    cor: '#13c2c2',
    icone: 'HeartOutlined',
    permissoes: {
      pacientes:   { criar: true,  editar: true,  visualizar: true,  excluir: false },
      agendamento: { criar: false, editar: false, visualizar: true,  cancelar: false},
      prontuario:  { criar: true,  editar: false, visualizar: true,  excluir: false },
      prescricao:  { criar: false, editar: false, visualizar: true,  excluir: false },
      medicacao:   { administrar: true, visualizar: true, criar: false, editar: false},
      exames:      { solicitar: false, liberar: false, visualizar: true, criar: false},
      internacao:  { admitir: false, alta: false, visualizar: true, criar: false     },
      medicos:     { criar: false, editar: false, visualizar: true,  excluir: false  },
      enfermeiros: { criar: false, editar: false, visualizar: true,  excluir: false  },
      usuarios:    { criar: false, editar: false, visualizar: false, excluir: false  },
      alas:        { criar: false, editar: false, visualizar: true,  excluir: false  },
      leitos:      { criar: false, editar: false, visualizar: true,  excluir: false  },
      faturamento: { criar: false, editar: false, visualizar: false, excluir: false  },
      relatorios:  { visualizar: false, exportar: false                              },
      roles:       { criar: false, editar: false, visualizar: false, excluir: false  },
      sistema:     { administrar: false                                              },
    },
  },
  RECEPCIONISTA: {
    label: 'Recepcionista',
    descricao: 'Cadastro de pacientes e agendamento',
    cor: '#722ed1',
    icone: 'TeamOutlined',
    permissoes: {
      pacientes:   { criar: true,  editar: true,  visualizar: true,  excluir: false },
      agendamento: { criar: true,  editar: true,  visualizar: true,  cancelar: true },
      prontuario:  { criar: false, editar: false, visualizar: false, excluir: false },
      prescricao:  { criar: false, editar: false, visualizar: false, excluir: false },
      medicacao:   { administrar: false, visualizar: false, criar: false, editar: false},
      exames:      { solicitar: false, liberar: false, visualizar: true, criar: false },
      internacao:  { admitir: false, alta: false, visualizar: true, criar: false      },
      medicos:     { criar: false, editar: false, visualizar: true,  excluir: false   },
      enfermeiros: { criar: false, editar: false, visualizar: true,  excluir: false   },
      usuarios:    { criar: false, editar: false, visualizar: false, excluir: false   },
      alas:        { criar: false, editar: false, visualizar: true,  excluir: false   },
      leitos:      { criar: false, editar: false, visualizar: true,  excluir: false   },
      faturamento: { criar: false, editar: false, visualizar: false, excluir: false   },
      relatorios:  { visualizar: false, exportar: false                               },
      roles:       { criar: false, editar: false, visualizar: false, excluir: false   },
      sistema:     { administrar: false                                               },
    },
  },
  FARMACEUTICO: {
    label: 'Farmacêutico(a)',
    descricao: 'Gestão de estoque, dispensação e validação de prescrições',
    cor: '#52c41a',
    icone: 'ExperimentOutlined',
    permissoes: {
      pacientes:   { criar: false, editar: false, visualizar: true,  excluir: false },
      agendamento: { criar: false, editar: false, visualizar: false, cancelar: false},
      prontuario:  { criar: false, editar: false, visualizar: true,  excluir: false },
      prescricao:  { criar: false, editar: false, visualizar: true,  excluir: false },
      medicacao:   { administrar: false, visualizar: true, criar: true, editar: true },
      exames:      { solicitar: false, liberar: false, visualizar: true, criar: false},
      internacao:  { admitir: false, alta: false, visualizar: true, criar: false     },
      medicos:     { criar: false, editar: false, visualizar: true,  excluir: false  },
      enfermeiros: { criar: false, editar: false, visualizar: false, excluir: false  },
      usuarios:    { criar: false, editar: false, visualizar: false, excluir: false  },
      alas:        { criar: false, editar: false, visualizar: true,  excluir: false  },
      leitos:      { criar: false, editar: false, visualizar: false, excluir: false  },
      faturamento: { criar: false, editar: false, visualizar: false, excluir: false  },
      relatorios:  { visualizar: true, exportar: false                               },
      roles:       { criar: false, editar: false, visualizar: false, excluir: false  },
      sistema:     { administrar: false                                              },
    },
  },
  FATURAMENTO: {
    label: 'Faturamento',
    descricao: 'Guias, convênios, TISS e relatórios financeiros',
    cor: '#fa8c16',
    icone: 'DollarOutlined',
    permissoes: {
      pacientes:   { criar: false, editar: false, visualizar: true,  excluir: false },
      agendamento: { criar: false, editar: false, visualizar: true,  cancelar: false},
      prontuario:  { criar: false, editar: false, visualizar: false, excluir: false },
      prescricao:  { criar: false, editar: false, visualizar: false, excluir: false },
      medicacao:   { administrar: false, visualizar: false, criar: false, editar: false},
      exames:      { solicitar: false, liberar: false, visualizar: true, criar: false },
      internacao:  { admitir: false, alta: false, visualizar: true, criar: false      },
      medicos:     { criar: false, editar: false, visualizar: true,  excluir: false   },
      enfermeiros: { criar: false, editar: false, visualizar: false, excluir: false   },
      usuarios:    { criar: false, editar: false, visualizar: false, excluir: false   },
      alas:        { criar: false, editar: false, visualizar: true,  excluir: false   },
      leitos:      { criar: false, editar: false, visualizar: true,  excluir: false   },
      faturamento: { criar: true,  editar: true,  visualizar: true,  excluir: false   },
      relatorios:  { visualizar: true, exportar: true                                 },
      roles:       { criar: false, editar: false, visualizar: false, excluir: false   },
      sistema:     { administrar: false                                               },
    },
  },
  SOMENTE_LEITURA: {
    label: 'Somente Leitura',
    descricao: 'Apenas visualização — auditores e gestores externos',
    cor: '#8c8c8c',
    icone: 'EyeOutlined',
    permissoes: {
      pacientes:   { criar: false, editar: false, visualizar: true,  excluir: false },
      agendamento: { criar: false, editar: false, visualizar: true,  cancelar: false},
      prontuario:  { criar: false, editar: false, visualizar: true,  excluir: false },
      prescricao:  { criar: false, editar: false, visualizar: true,  excluir: false },
      medicacao:   { administrar: false, visualizar: true, criar: false, editar: false},
      exames:      { solicitar: false, liberar: false, visualizar: true, criar: false },
      internacao:  { admitir: false, alta: false, visualizar: true, criar: false      },
      medicos:     { criar: false, editar: false, visualizar: true,  excluir: false   },
      enfermeiros: { criar: false, editar: false, visualizar: true,  excluir: false   },
      usuarios:    { criar: false, editar: false, visualizar: false, excluir: false   },
      alas:        { criar: false, editar: false, visualizar: true,  excluir: false   },
      leitos:      { criar: false, editar: false, visualizar: true,  excluir: false   },
      faturamento: { criar: false, editar: false, visualizar: false, excluir: false   },
      relatorios:  { visualizar: true, exportar: false                                },
      roles:       { criar: false, editar: false, visualizar: false, excluir: false   },
      sistema:     { administrar: false                                               },
    },
  },
};